### ISSUE TITLE
best-effort set with actual alleles?

### ISSUE THREAD

**Issue by brentp** [lh3/CHM-eval#1]
I understand the reason behind simply providing the locations, but in many real-world scenarios, especially in coding regions, it's important to get the exact variant correctly.

Is there any plan to provide a syndip set with the REF and ALT alleles inferred from the pac-bio data?

**Comment by lh3** [comment]
Not sure what you mean by "actual alleles". Do you mean phasing?

**Comment by brentp** [comment]
nevermind. I originally just saw the bed files.
