### ISSUE TITLE
hg38 bam available?

### ISSUE THREAD

**Issue by jjfarrell** [lh3/CHM-eval#2]
Is there a hg38 aligned bam (Illumina reads) available for download for CHM1, CHM13 and CHM1_CHM13?  I've just been able to find the hs37 aligned bams.

**Comment by lh3** [comment]
In the Broad file system, you can find the bwa-mem alignment at `/home/unix/hengli/CHM/33remap/msb2.m38.bam`. This has not gone through the best practice pipeline – i.e. no realignment or BQSR, though at my hand, the additional steps often make little difference.

The hs37 BAM at ENA was generated with the Broad production pipeline.

**Comment by lh3** [comment]
Not available outside Broad, unfortunately.
