### ISSUE TITLE
Missing run-flt in release

### ISSUE THREAD

**Issue by bballew** [lh3/CHM-eval#5]
I downloaded the 20180222 release version, but it doesn't appear to include the run-flt script.  So, I cloned the master branch, which does have the run-flt script, but has a very different directory structure than what's described in the readme.  When I try to run run-flt, I get error messages like this: 
```
sh: CHM-eval/k8: No such file or directory
sh: CHM-eval/k8: No such file or directory
sh: CHM-eval/k8: No such file or directory
sh: CHM-eval/htsbox: No such file or directory
sh: CHM-eval/htsbox: No such file or directory
``` 

You may need to include the run-flt script in the release, and/or update paths/documentation for the master branch.

Thanks!

**Comment by lh3** [comment]
You can copy run-flt to directory "CHM-eval.kit".
