### ISSUE TITLE
Variants out of range in rep2.37.broad.hc.raw.vcf.gz

### ISSUE THREAD

**Issue by wdecoster** [lh3/CHM-eval#7]
Hi Heng,

I noticed that there are variants in rep2.37.broad.hc.raw.vcf.gz that are out of range of their chromosomes. An example is on chromosome 9, position 138395067.
I did not look into this in any further detail.

Is there another vcf you would recommend as truth set for syndip? Or would it be best to filter in this vcf.

Thanks,
Wouter

**Comment by lh3** [comment]
The length of chr9 is 141213431.

**Comment by wdecoster** [comment]
Thanks, it turns I'm using the wrong genome build. Is there a GRCh38 syndip truth set?

**Comment by lh3** [comment]
That is not truth set. See readme.

**Comment by wdecoster** [comment]
Oh, I'm sorry, but that was not obvious to me. The readme mentions that the truth set can be found in the Releases, but then I assume I should use the one in CHM-evalkit-20180222.tar, i.e. full.38.vcf.gz?

**Comment by lh3** [comment]
Well, readme provides a wget link and the description of major files in the tarballs. When using the truth data, you should also follow the readme instruction.
